### ISSUE TITLE
Company field not working

### ISSUE THREAD

**Issue by craigmarcussen** [concretecms-community-store/community_store#682]
Hello,

In the settings, I enabled the **Company Name** as **Optional**, but I have noticed that it usually doesn't work. It shows the label correctly at checkout, but the input value is blank. When I set the **Company Name** to **Required**, it seems to work correctly.

I am using CS 2.3.4 in Concrete 8.5.5.

**Comment by Mesuva** [comment]
You're right, this just wasn't coded correctly - I've pushed up some fixes.

**Comment by craigmarcussen** [comment]
That seems to have fixed it. Thank you for the speedy reply (as always), and have a great weekend!

**Comment by craigmarcussen** [comment]
Hello,

Having spent a little more time with this, I have noticed a small bug still exists.

If I check out with the Company field filled out on in the **Billing Details** form, and select the **Use these details for shipping** option, the Company field is populated in the **Shipping Address** block, but not the **Billing Details** block (in the Checkout Summary). If I don't select the **Use these details for shipping** option, and fill in the Company field again in the **Shipping Address** form, it shows up in both places.

This only seems to happens the first time I go through the process. If I use autofill to go through the checkout again, it works in both scenarios.

It's a small issue, but it could be confusing to the user if they don't see the Company filed properly populated in the first instance.

**Comment by Mesuva** [comment]
I've not been able to replicate this last bug you mentioned. 
If I open up a new browser/session, fill in the checkout, a put a company name in, check the use details checkbox and continue, the company name shows up in the summary box for both billing and shipping.

Perhaps it's been fixed along the way, or you were using cached javascript?
