### ISSUE TITLE
Upgrade to 9.2.3 get me this Entity 'Concrete\Package\CommunityStore\Entity\Attribute\Key\StoreOrderKey'

### ISSUE THREAD

**Issue by baxterdmutt** [concretecms-community-store/community_store#827]
Doctrine \ ORM \ Mapping \ MappingException
Entity 'Concrete\Package\CommunityStore\Entity\Attribute\Key\StoreOrderKey' has to be part of the discriminator map of 'Concrete\Core\Entity\Attribute\Key\Key' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Concrete\Package\CommunityStore\Entity\Attribute\Key\StoreOrderKey' an abstract class to avoid this exception from occurring.

It happens when I click on the "Store" in the Dashboard.  The store seems to be working however.
I am sorry. I seem to be the one that has been having so many problems.

**Comment by baxterdmutt** [comment]
Well, I fixed this one myself.  I rebuilt the database entities and that seems to have it working again.

**Comment by Mesuva** [comment]
Great, it's something with a potential fix in the pipeline, but I haven't had the chance to implement it yet.

**Comment by ccmEnlil** [comment]
This is still an issue.  I just caked an entire test installation trying to upgrade to 9.3.3.  Hit this exact error on the upgrade complete page...

**Comment by Mesuva** [comment]
I _thought_ this has been fixed from the updates made in version 2.7, but obviously not.

Doctrine and cache refreshes have always solved it for me. Do you have lots of add-ons installed?

**Comment by ccmEnlil** [comment]
Aha!  Thought i was running latest.  i was not.  Already whacked the site and got it up fresh again.  Just a test bed with a couple add ons installed.  I'll install latest and run update to 9.3.4 to see what happens.

**Comment by ccmEnlil** [comment]
Negative.  Installed fresh 9.3.2.  Manually upgraded to 9.3.3 via updates folder.  Installed latest Store.  Immediately ran upgrade to 9.3.4 and hit the error on the upgrade success page!

![storeerror](https://github.com/user-attachments/assets/f8d3e1eb-5d38-45cb-9969-4df0dc588082)

Every page including dashboard is broken...

Whoops \ Exception \ ErrorException (E_WARNING)
require(xxx/xxx/xxx/application/config/doctrine/proxies/__CG__ConcreteCoreEntitySiteSiteTree.php): failed to open stream: No such file or directory

**Comment by Mesuva** [comment]
This one doesn't appear to be a Community Store specific issue, just broken Doctrine entities.

What I would suggest is just finding the file __CG__ConcreteCoreEntitySiteSiteTree.php, from the same location, from another 9.3.x install and copying that into place. You may need to do that a few times, until you can get the dashboard up, and then trigger a Doctrine refresh.
